-- =========================================
-- RIS Lite - Schema Supabase
-- =========================================

-- =========================
-- roles
-- =========================
CREATE TABLE IF NOT EXISTS public.roles (
  id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE
);

-- =========================
-- usuarios
-- =========================
CREATE TABLE IF NOT EXISTS public.usuarios (
  id UUID PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  rol TEXT NOT NULL,
  activo BOOLEAN DEFAULT TRUE
);

-- =========================
-- pacientes
-- =========================
CREATE TABLE IF NOT EXISTS public.pacientes (
  id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  fecha_nacimiento DATE,
  activo BOOLEAN DEFAULT TRUE
);

-- =========================
-- medico_solicitante
-- =========================
CREATE TABLE IF NOT EXISTS public.medico_solicitante (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  especialidad TEXT,
  activo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- tipo_examen
-- =========================
CREATE TABLE IF NOT EXISTS public.tipo_examen (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  codigo TEXT,
  activo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  descripcion TEXT
);

-- =========================
-- estado_orden
-- =========================
CREATE TABLE IF NOT EXISTS public.estado_orden (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  orden INT8 NOT NULL,
  activo BOOLEAN DEFAULT TRUE
);

-- =========================
-- orden_radiologica
-- =========================
CREATE TABLE IF NOT EXISTS public.orden_radiologica (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INT4 NOT NULL,
  medico_id INT8 NOT NULL,
  tipo_examen_id INT8 NOT NULL,
  estado_id INT8 NOT NULL,
  prioridad TEXT NOT NULL,
  observacion TEXT,
  activo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID,
  CONSTRAINT fk_orden_paciente FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT fk_orden_medico FOREIGN KEY (medico_id) REFERENCES public.medico_solicitante(id),
  CONSTRAINT fk_orden_tipo_examen FOREIGN KEY (tipo_examen_id) REFERENCES public.tipo_examen(id),
  CONSTRAINT fk_orden_estado FOREIGN KEY (estado_id) REFERENCES public.estado_orden(id),
  CONSTRAINT fk_orden_usuario FOREIGN KEY (created_by) REFERENCES public.usuarios(id)
);

-- =========================
-- log_sistema
-- =========================
CREATE TABLE IF NOT EXISTS public.log_sistema (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidad TEXT NOT NULL,
  entidad_id INT8 NOT NULL,
  accion TEXT NOT NULL,
  detalle TEXT,
  user_email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- indices
-- =========================
CREATE INDEX IF NOT EXISTS idx_orden_estado ON public.orden_radiologica(estado_id);
CREATE INDEX IF NOT EXISTS idx_orden_paciente ON public.orden_radiologica(paciente_id);
CREATE INDEX IF NOT EXISTS idx_orden_medico ON public.orden_radiologica(medico_id);
CREATE INDEX IF NOT EXISTS idx_orden_fecha ON public.orden_radiologica(created_at);
CREATE INDEX IF NOT EXISTS idx_log_entidad ON public.log_sistema(entidad, entidad_id);
CREATE INDEX IF NOT EXISTS idx_usuario_rol ON public.usuarios(rol);

